# Generated by Django 3.2.13 on 2024-07-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='emailS',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
