# Generated by Django 3.2.13 on 2024-08-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_service_persserv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
